apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-billing
  tags:
    - nodejs
  links:
    - title: Gitlab
      url: https://gitlab.uisee.ai/cloud/service/billing-service
    - title: Documentation
      url: https://gitlab.uisee.ai/cloud/service/billing-service/-/tree/feature/swagger_auto_create_api_doc/doc
  annotations:
    gitlab.com/project-id: '2410'
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: published
  owner: frontend-satellite
  system: billing
  providesApis: [service-billing-wechat-api]

---

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  tags: [1-0-0]
  name: service-billing-wechat-api
  description: The billing API description
spec:
  type: openapi
  lifecycle: published
  owner: user:zhiheng.song
  system: billing-service
  definition: |
    openapi: 3.0.0
    paths:
      /wechat/createOrder:
        post:
          operationId: WechatController_createOrder
          summary: Create Order
          parameters: []
          requestBody:
            required: true
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/WechatCreateOrderDto"
          responses:
            "200":
              description: ""
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/IWechatOrder"
          tags:
            &a1
            - wechat
    info:
      title: wechat-APIs
      description: The billing API description
      version: "1.0"
      contact: {}
    tags: []
    servers: []
    components:
      schemas:
        WechatCreateOrderDto:
          type: object
          properties:
            out_trade_no:
              type: string
              example: "1234566789"
              description: 内部订单 id
            user_external_id:
              type: string
              example: "1234566789"
              description: 用户外部订单id
            trips:
              example:
                - "1"
                - "2"
                - "3"
              description: 行程列表
              type: array
              items:
                type: string
            trip_mileage:
              type: number
              example: 2.22
              description: 实际行驶距离 km
            trip_price:
              type: number
              example: 10.01
              description: 行程价格
            trip_estimated_mileage:
              type: number
              example: 1.23
              description: 实际行程距离 km
            trip_estimated_time:
              type: number
              example: 3600
              description: 预计行程时间 单位（秒）
            trip_estimated_price:
              type: number
              example: 10.01
              description: 预计行程价格，预设字段，固定传 0
            status:
              type: number
              example: 0
              description: 订单状态：0 初始， 1 调度中， 2 服务中， 3 成功， 4 中止
            pay_status:
              type: number
              example: 0
              description: 支付状态：0 未支付 1 已支付
            schedule_status:
              type: number
              example: 0
              description: 调度状态：0 失败 1 成功 2 未响应
            user_id:
              type: string
              example: user
              description: 订单用户id
            identity:
              type: string
              example: DEFAULT
              enum:
                - DEFAULT
                - VIP
              description: 用户身份
          required:
            - out_trade_no
            - user_external_id
            - trips
            - trip_mileage
            - trip_price
            - trip_estimated_mileage
            - trip_estimated_time
            - trip_estimated_price
            - status
            - pay_status
            - schedule_status
            - user_id
            - identity
        IWechatOrder:
          type: object
          properties:
            id:
              type: string
              example: ""
              description: 订单自增 uuid
            appid:
              type: string
              example: wx123912389sxxx
              description: 公众账号 appid 或 应用id
            mch_id:
              type: string
              example: 1304135001xxxx
              description: 微信支付商户号
            time_expire:
              type: string
              example: 1655276830966
              description: 订单过期时间
            prepay_id:
              type: string
              example: 12329332xxxxx
              description: 订单临时号 有效期 2 小时
            out_trade_no:
              type: string
              example: "18923923823233"
              description: 订单号
            vehicle_external_id:
              type: string
              example: e100.car3
              description: 车辆外部 id
            user_external_id:
              type: string
              example: "18923923823233"
              description: 客户外部订单 id
            trips:
              example:
                - "1"
                - "2"
                - "3"
              description: 行程站点 id 列表
              type: array
              items:
                type: string
            trip_mileage:
              type: number
              example: 2.22
              description: 实际行程距离 km
            trip_time:
              type: number
              example: 1655276830966
              description: 实际行程时间
            trip_estimated_mileage:
              type: number
              example: 3600
              description: 预计行程时间 单位（秒）
            trip_estimated_time:
              type: number
              example: 10.01
              description: 预计行程价格，预设字段，固定传 0
            status:
              type: number
              example: 0
              description: 订单状态：0 初始， 1 调度中， 2 服务中， 3 成功， 4 中止
            pay_status:
              type: number
              example: 0
              description: 支付状态 0 未支付 1已支付
            schedule_status:
              type: number
              example: 0
              description: 调度状态：0 失败 1 成功 2 未响应
          required:
            - id
            - appid
            - mch_id
            - time_expire
            - prepay_id
            - out_trade_no
            - vehicle_external_id
            - user_external_id
            - trips
            - trip_mileage
            - trip_time
            - trip_estimated_mileage
            - trip_estimated_time
            - status
            - pay_status
            - schedule_status
