site_name: docs-test-fixture
site_description: Documentation site test fixture

nav:
  - Home: index.md
  - Getting Started: 'getting-started/index.md'
  - SubDocs: '!include ./docs/sub-docs/mkdocs.yml'
  - Plugins: '*include ./docs/plugins/*/mkdocs.yml'

plugins:
  - techdocs-core
