apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: billing-service
  description: |
    support create order payment
  links:
    - title: Github
      url: https://github.com/lancelot-song/backstage-app
    - title: Documentation
      url: https://github.com/lancelot-song/backstage-app/blob/feature/docs/docs/index.md
  annotations:
    github.com/project-slug: lancelot-song/backstage-app
spec:
  type: service
  lifecycle: production
  owner: cloud
  providesApis: [wechat-APIs]